services:
  mssql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    hostname: mssql_server
    build: 
      context: .
      dockerfile: db/Dockerfile
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    networks:
      - udemy-network
  rest-with-aspnet:
    image: ${DOCKER_REGISTRY-}restwithaspnet
    container_name: rest-with-aspnet
    hostname: rest-with-aspnet
    build:
      context: .
      dockerfile: RestWithASPNet/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production 
      TZ: America/Sao_Paulo
    ports:
      - 5000:8080
    depends_on:
      - mssql_server
    networks:
      - udemy-network

networks:
  udemy-network:
    driver: bridge