services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver
    build: 
      context: .
      dockerfile: db/Dockerfile
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    networks:
      - udemy-network
  rest-with-aspnet:
    image: ${DOCKER_REGISTRY-}restwithaspnet
    hostname: rest-with-aspnet
    build:
      context: .
      dockerfile: RestWithASPNet/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production 
      TZ: America/Sao_Paulo
    ports:
      - 44300:80
    depends_on:
      - sqlserver
    networks:
      - udemy-network

networks:
  udemy-network:
    driver: bridge