services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  rest-with-aspnet:
    image: ${DOCKER_REGISTRY-}restwithaspnet
    build:
      context: .
      dockerfile: RestWithASPNet/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production 
